export enum SESSION_STATUS {
  ACTIVE = "ACTIVE",
  EXPIRED = "EXPIRED",
  LOGOUT_ALL = "ALL LOGOUT",
  LOGOUT_FORCE = "FORCE LOGOUT",
  LOGOUT_SELF = "SELF LOGOUT",
  PW_CHANGE = "PASSWORD CHANGE",
  PW_FORGOT = "PASSWORD FORGOT",
}
